ibw_jobeet_ibw_job:
    resource: "@IbwJobeetBundle/Resources/config/routing/job.yml"
    prefix:   /

ibw_jobeet_homepage:
    path:     /default
    defaults: { _controller: IbwJobeetBundle:Default:index }